### ISSUE TITLE
There is a mistake in errors handling?

### ISSUE THREAD

**Issue by mklkun** [takluyver/bash_kernel#92]
In console whenever there is an error in an executed block, when we try to save the notebook we get this error message:

```
Notebook JSON is invalid: Additional properties are not allowed ('execution_count' was unexpected)
    
    Failed validating 'additionalProperties' in error:
    
    On instance['cells'][1]['outputs'][1]:
    {'ename': '',
     'evalue': '127',
     'execution_count': 2,
     'output_type': 'error',
     'traceback': []}
```

Do you have any explanation or fix please?

**Comment by takluyver** [comment]
The messaging docs have a discrepancy about whether the kernel should send that field or not with the error message: https://github.com/jupyter/jupyter_client/issues/129. I guess if it causes the notebook to fail validation, that suggests that most kernels don't, and thus we should probably update the docs to say so.

**Comment by takluyver** [comment]
Should be fixed by 7475e10a31b2218147d4bfa2373e3e13c01536e1. Can you try it from master? If it works, I'll make a new release.

**Comment by mklkun** [comment]
Great! It works fine for me in this way. I still do not understand though, why there is this error message since in `ipykernel` this field is provided whatever the status is.

**Comment by takluyver** [comment]
There are two error messages sent by the kernel - the `execute_reply` message with `"status": "error"`, and the `error` output message. The former should have an execution count (at least, it does in ipykernel), but the latter shouldn't, and that was the issue here.

**Comment by mklkun** [comment]
I see. Thanks for your explanations!

**Comment by takluyver** [comment]
Follow up: my clarifications to the messaging doc were merged, and I've released bash_kernel 0.7.2 with the fix.

**Comment by mklkun** [comment]
Great! Thanks for the notification.
